// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Architecture.Seedwork.Domain;
#nullable disable

namespace FinanceManagement.Domain
{
    [Table("fm_pigoriginalassetsdetail")]
    //[Index(nameof(NumericalOrder), nameof(EarNumber), Name = "Num_EarNumber")]
    public partial class FmPigoriginalassetsdetail : EntityBase
    {
        /// <summary>
        /// 流水号
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 耳号
        /// </summary>
        [Key]
        [Column(TypeName = "bigint(20)")]
        public string EarNumber { get; set; }
        /// <summary>
        /// 猪只类型
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string PigType { get; set; }
        /// <summary>
        /// 原值
        /// </summary>
        public decimal? OriginalValue { get; set; }
        /// <summary>
        /// 折旧年限（月）
        /// </summary>
        [Column(TypeName = "int(11)")]
        public int? DepreciationUseMonth { get; set; }
        /// <summary>
        /// 净残值率（%）
        /// </summary>
        public decimal? ResidualValueRate { get; set; }
        /// <summary>
        /// 净残值
        /// </summary>
        public decimal? ResidualValue { get; set; }
        /// <summary>
        /// 开始使用日期
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime StartDate { get; set; }
        /// <summary>
        /// 已计提月份
        /// </summary>
        [Column(TypeName = "int(11)")]
        public int? AccruedMonth { get; set; }
        /// <summary>
        /// 累计折旧
        /// </summary>
        public decimal? DepreciationAccumulated { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        [Column(TypeName = "timestamp")]
        public DateTime ModifiedDate { get; set; }
    }
}