// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinanceManagement.Infrastructure.QlwCrossDbEntities
{
    public class FD_IdentificationTypeODataEntity
    {
        [Key]
        public string TypeID { get; set; }
        public string TypeName { get; set; }
        public string NumericalOrder { get; set; }
        public string EnterpriseID { get; set; }
        public int? BusiType { get; set; }
        public int? AccrualType { get; set; }
        //public int? DataSourceType { get; set; }
        public string Remarks { get; set; }
        public string OwnerID { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
    }
    public class fd_identificationtypeBaseODataEntity
    {
        public string TypeID { get; set; }
        public string TypeName { get; set; }
    }
}