// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
namespace FinanceManagement.Infrastructure.QlwCrossDbEntities
{
    public partial class FD_IdentificationTypeSubjectODataEntity
    {
        [Key]
        public int RecordID { get; set; }
        public string TypeID { get; set; }
        public string AccoSubjectID { get; set; }
        public string AccoSubjectCode { get; set; }
        public string NumericalOrder { get; set; }
        public string EnterpriseID { get; set; }
        public bool? IsUse { get; set; }
        public string OwnerID { get; set; }
        public string CreatedDate { get; set; }
        public string ModifiedDate { get; set; }
        public int? Rank { get; set; }
        public string TypeName { get; set; }
        public bool? IsPerson { get; set; }
        public int? DataSourceType { get; set; }
    }
    public class FD_IdentificationTypeAndSubjectODataEntity
    {
        [Key]
        public int RecordID { get; set; }
        public string TypeID { get; set; }
        public string OldTypeID { get; set; }
        public string TypeName { get; set; }
        public string NumericalOrder { get; set; }
        public int? BusiType { get; set; }
        public int? AccrualType { get; set; }
        public string AccoSubjectID { get; set; }
        //public string AccoSubjectCode { get; set; }
        public string AccoSubjectFullName { get; set; }
        public bool IsUse { get; set; }
        public int? DataSourceType { get; set; }
        public string DataSourceTypeName { get; set; }
    }    
}