// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Common.Application.Query;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Infrastructure.QlwCrossDbEntities
{
    public class MS_FormulaProductPriceODataEntity : OneWithManyQueryEntity<MS_FormulaProductPriceDetailODataEntity>
    {

        [Key]
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 集团ID
        /// </summary>
        public string GroupID { get; set; }
        /// <summary>
        /// 日期
        /// </summary>
        public string DataDate { get; set; }
        /// <summary>
        /// 单据号
        /// </summary>
        public string Number { get; set; }
        /// <summary>
        /// 制单人
        /// </summary>
        public string OwnerID { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 最后修改日期
        /// </summary>
        public DateTime ModifiedDate { get; set; }
        /// <summary>
        /// 制单人名称
        /// </summary>
        public string OwnerName { get; set; }
        /// <summary>
        /// 审核人
        /// </summary>

        public string CheckedByID { get; set; }
        /// <summary>
        /// 审核人名称
        /// </summary>
        public string CheckedByName { get; set; }
       
        /// <summary>
        /// 账务单位名称
        /// </summary>
        public string EnterpriseName { get; set; }
        /// <summary>
        /// 审核状态  0：未审 1:已审
        /// </summary>
        public int CheckState { get; set; }
        /// <summary>
        /// 账务单位
        /// </summary>
        [NotMapped]
        public List<string> EnterpriseList { get; set; } = new List<string>();
        /// <summary>
        /// 账务单位名称
        /// </summary>
        [NotMapped]
        public List<string> EnterpriseNameList { get; set; } = new List<string>();
    }
    public class MS_FormulaProductPriceDetailODataEntity
    {
        [Key]
        /// <summary>
        /// RecordID
        /// </summary>		
        public int RecordID { get; set; }     
        /// <summary>
        /// NumericalOrder
        /// </summary>		
        public string NumericalOrder { get; set; }

        /// <summary>
        /// 商品ID
        /// </summary>
        public string ProductID { get; set; }
        /// <summary>
        /// 规格
        /// </summary>
        public string Specification { get; set; }
        /// <summary>
        /// 标包
        /// </summary>
        public decimal? StandardPack { get; set; }
        /// <summary>
        /// 计量单位
        /// </summary>
        public string MeasureUnit { get; set; }

        /// <summary>
        /// 市场单价
        /// </summary>

        public decimal MarketPrice { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 最后修改日期
        /// </summary>

        public DateTime ModifiedDate { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        public string ProductName { get; set; }
        /// <summary>
        /// 计量单位名称
        /// </summary>
        public string MeasureUnitName { get; set; }
    }


    /// <summary>
    /// 扩展表
    /// </summary>
    public class MS_FormulaProductPriceExtODataEntity
    {
        [Key]
        public int RecordID { get; set; }
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 单位ID
        /// </summary>
        public string EnterpriseID { get; set; }
        /// <summary>
        /// 单位名称
        /// </summary>
        public string EnterpriseName { get; set; }
        public DateTime ModifiedDate { get; set; }
    }

    public class MS_FormulaProductPriceValidODataEntity
    {
        [Key]
        public string Guid { get; set; }
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 单据号
        /// </summary>
        public string Number { get; set; }
        /// <summary>
        /// 商品ID
        /// </summary>
        public string ProductID { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        public string ProductName { get; set; }
        /// <summary>
        /// 单位名称
        /// </summary>
        [NotMapped]
        public string EnterpriseName { get; set; }
        //[NotMapped]
        //public List<string> EnterpriseList { get; set; } = new List<string>();
    }

    public class MS_FormulaProductPriceExportODataEntity
    {
        //单据号 账务单位    日期 商品代号    规格 标包  计量单位 市场单价    备注
        /// <summary>
        /// 单据号
        /// </summary>
        public string Number { get; set; }
        /// <summary>
        /// 账务单位名称
        /// </summary>
        public string EnterpriseName { get; set; }
        /// <summary>
        /// 日期
        /// </summary>
        public string DataDate { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        public string ProductName { get; set; }
        /// <summary>
        /// 规格
        /// </summary>
        public string Specification { get; set; }
        /// <summary>
        /// 标包
        /// </summary>
        public decimal? StandardPack { get; set; }
        /// <summary>
        /// 计量单位
        /// </summary>
        public string MeasureUnitName { get; set; }

        /// <summary>
        /// 市场单价
        /// </summary>

        public decimal MarketPrice { get; set; }

        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        public string NumericalOrder { get; set; }
        [Key]
        public string Guid { get; set; }
    }
}