// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Infrastructure;
using FinanceManagement.Domain;
using FinanceManagement.Domain.MarketingProductCostSettingManagement;
using FinanceManagement.Infrastructure.EntityConfigurations;
using FinanceManagement.Infrastructure.EntityConfigurations.MarketingProductCostSettingManagement;
using FinanceManagement.Infrastructure.QlwCrossDbEntities;
using MediatR;
using Microsoft.EntityFrameworkCore;
using System.Collections.Generic;
using System.Data;
using System.Dynamic;
using System.Reflection;
using System;
using System.Linq;
using Newtonsoft.Json;
using System.Text.RegularExpressions;

namespace FinanceManagement.Infrastructure
{
    public partial class QlwCrossDbContext : DbContext
    {
        //坏账参数设置
        public DbSet<FD_BaddebtSettingODataEntity> FD_BaddebtSettingDataSet { get; set; }
        public DbSet<FD_BaddebtSettingDetailODataEntity> FD_BaddebtSettingDetailDataSet { get; set; }
        public DbSet<FD_BaddebtGroupSettingODataEntity> FD_BaddebtGroupSettingDataSet { get; set; }
        public DbSet<FD_BaddebtGroupSettingDetailODataEntity> FD_BaddebtGroupSettingDetailDataSet { get; set; }
        public DbSet<FD_BaddebtGroupSettingExtendODataEntity> FD_BaddebtGroupSettingExtendDataSet { get; set; }
        public DbSet<DropSubject> FD_SubjectDataSet { get; set; }
        public DbSet<FD_AgingDetaiODataEntity> FD_AgingDetaiODataEntity { get; set; }

        public DbSet<FD_AccountTransferODataEntity> FD_AccountTransferDataSet { get; set; }

        public DbSet<FD_AccountTransferDetailODataEntity> FD_AccountTransferDetailDataSet { get; set; }

        public DbSet<FD_AccountInventoryODataEntity> FD_AccountInventoryDataSet { get; set; }

        public DbSet<FD_AccountInventoryDetailODataEntity> FD_AccountInventoryDetailDataSet { get; set; }

        public DbSet<FD_CapitalBudgetODataEntity> FD_CapitalBudgetDataSet { get; set; }

        public DbSet<FD_CapitalBudgetDetailODataEntity> FD_CapitalBudgetDetailDataSet { get; set; }
        //余额调节表
        public DbSet<FD_BalanceadJustmentODataEntity> FD_BalanceadJustmentDataSet { get; set; }

        public DbSet<FD_BalanceadJustmentDetailODataEntity> FD_BalanceadJustmentDetailDataSet { get; set; }

        public DbSet<AuditODataEntity> AuditDataSet { get; set; }

        public DbSet<FD_CashSweepODataEntity> CashSweepDataSet { get; set; }

        public DbSet<FD_AccountODataEntity> FD_AccountDataSet { get; set; }
        public DbSet<BIZ_DataDictODataEntity> BIZ_DataDictDataSet { get; set; }
        public DbSet<TreeModelODataEntity> TreeModelDataSet { get; set; }
        public DbSet<TreeModelExtityODataEntity> TreeModelExtityDataSet { get; set; }

        public DbSet<FM_CarryForwardVoucherODataEntity> FM_CarryForwardVoucherDataSet { get; set; }
        public DbSet<FM_CarryForwardVoucherDetailODataEntity> FM_CarryForwardVoucherDetailDataSet { get; set; }
        public DbSet<FM_CarryForwardVoucherExtendODataEntity> FM_CarryForwardVoucherExtendDataSet { get; set; }
        public DbSet<FM_CarryForwardVoucherFormulaODataEntity> FM_CarryForwardVoucherFormulaDataSet { get; set; }
        public DbSet<FM_CarryForwardVoucherRecordODataEntity> FM_CarryForwardVoucherRecordDataSet { get; set; }

        public DbSet<FM_NewCarryForwardVoucherODataEntity> FM_NewCarryForwardVoucherDataSet { get; set; }
        public DbSet<FM_NewCarryForwardVoucherDetailODataEntity> FM_NewCarryForwardVoucherDetailDataSet { get; set; }
        public DbSet<FM_NewCarryForwardVoucherExtendODataEntity> FM_NewCarryForwardVoucherExtendDataSet { get; set; }
        public DbSet<FM_NewCarryForwardVoucherFormulaODataEntity> FM_NewCarryForwardVoucherFormulaDataSet { get; set; }
        public DbSet<FM_NewCarryForwardVoucherRecordODataEntity> FM_NewCarryForwardVoucherRecordDataSet { get; set; }
        public DbSet<AdvanceCollectionODataEnetity> AdvanceCollectionDataSet { get; set; }
        public DbSet<ExpenseODataEnetity> ExpenseDataSet { get; set; }

        public DbSet<JXCModel> JXCDataSet { get; set; }
        public DbSet<FD_VoucherAmortizationODataEntity> FD_VoucherAmortizationDataSet { get; set; }
        public DbSet<FM_AccocheckoODataEntity> FM_AccocheckDataSet { get; set; }
        public DbSet<FD_VoucherAmortizationDetailODataEntity> FD_VoucherAmortizationDetailDataSet { get; set; }
        public DbSet<FD_VoucherAmortizationPeriodDetailODataEntity> FD_VoucherAmortizationPeriodDetailDataSet { get; set; }
        public DbSet<FD_VoucherAmortizationRecordODataEntity> FD_VoucherAmortizationRecordDataSet { get; set; }
        public DbSet<FM_VoucherAmortizationRelatedODataEntity> FM_VoucherAmortizationRelatedDataSet { get; set; }

        public DbSet<Biz_EnterpirseEntityODataEntity> Biz_EnterpirseEntityDataSet { get; set; }
        public DbSet<Biz_EnterprisePeriodODataEntity> Biz_EnterprisePeriodEntityDataSet { get; set; }

        public DbSet<FD_BadDebtProvisionODataEntity> FD_BadDebtProvisionDataSet { get; set; }

        public DbSet<FD_BadDebtProvisionExtODataEntity> FD_BadDebtProvisionExtDataSet { get; set; }
        public DbSet<FD_BadDebtProvisionDetailODataEntity> FD_BadDebtProvisionDetailDataSet { get; set; }

        public DbSet<FD_BadDebtProvisionListOnlyODataEntity> FD_BadDebtProvisionListOnlyDataSet { get; set; }

        public DbSet<FD_BadDebtOccurODataEntity> FD_BadDebtOccurDataSet { get; set; }
        #region 会计凭证导入专用
        /// <summary>
        /// 单位
        /// </summary>
        public DbSet<EnterpriseInfo> EnterpriseInfoDataSet { get; set; }
        /// <summary>
        /// 单据字
        /// </summary>
        public DbSet<TicketPointInfo> TicketPointInfoDataSet { get; set; }
        /// <summary>
        /// 摘要
        /// </summary>
        public DbSet<SettleSummaryInfo> SettleSummaryInfoDataSet { get; set; }
        /// <summary>
        /// 科目
        /// </summary>
        public DbSet<AccoSubjectInfo> AccoSubjectInfoDataSet { get; set; }
        /// <summary>
        /// 项目
        /// </summary>
        public DbSet<ProjectInfo> ProjectInfoDataSet { get; set; }
        /// <summary>
        /// 部门
        /// </summary>
        public DbSet<MarketInfo> MarketInfoDataSet { get; set; }
        /// <summary>
        /// ID Name 共用  用于 基础信息查询（类似 商品ID,名称）
        /// long 类型程序内部使用 不对外暴露
        /// </summary>
        public DbSet<KeyNameInfo> KeyNameInfoDataSet { get; set; }
        /// <summary>
        /// 人员
        /// </summary>
        public DbSet<PersonInfo> PersonInfoDataSet { get; set; }
        /// <summary>
        /// 单位id查集团id
        /// </summary>
        public DbSet<Biz_EnterpriseInfo> Biz_EnterpriseInfoDataSet { get; set; }
        //客户/供应商  二合一
        public DbSet<CusSupInfo> CusSupInfoDataSet { get; set; }
        /// <summary>
        /// 商品代号 商品名称 共用
        /// </summary>
        public DbSet<ProductsInfo> ProductInfoDataSet { get; set; }
        /// <summary>
        /// 商品分类
        /// </summary>
        public DbSet<ClassificationInfo> ClassificationInfoDataSet { get; set; }
        /// <summary>
        /// 资金账户
        /// </summary>
        public DbSet<AccountsInfo> AccountInfoDataSet { get; set; }
        /// <summary>
        /// 结算方式
        /// </summary>
        public DbSet<PayTypeInfo> PayTypeInfoDataSet { get; set; }
        #endregion
        #region 会计凭证导出
        public DbSet<ExportVoucher> ExportVoucherDataSet { get; set; }
        #endregion

        public DbSet<FD_BadDebtOccurListOnly> FD_BadDebtOccurListOnlyDataSet { get; set; }


        public DbSet<FD_BadDebtOccurDetailODataEntity> FD_BadDebtOccurDetailDataSet { get; set; }

        public DbSet<FD_BadDebtRecoverODataEntity> FD_BadDebtRecoverDataSet { get; set; }
        public DbSet<FD_BadDebtRecoverDetailODataEntity> FD_BadDebtRecoverDetailDataSet { get; set; }

        public DbSet<FD_BadDebtRecoverListOnly> FD_BadDebtRecoverListOnlyDataSet { get; set; }

        public DbSet<FD_PaymentReceivablesODataEntity> FD_PaymentReceivablesDataSet { get; set; }





        public DbSet<FD_BadDebtExecutionODataEntity> FD_BadDebtExecutionDataSet { get; set; }
        public DbSet<FD_SpecificIdentificationODataEntity> FD_SpecificIdentificationDataSet { get; set; }
        public DbSet<FD_SpecificIdentificationDetailODataEntity> FD_SpecificIdentificationDetailDataSet { get; set; }

        public DbSet<FD_SpecificIdentificationRangeODataEntity> FD_SpecificIdentificationRangeDataSet { get; set; }

        public DbSet<FD_SpecificIdentificationExtODataEntity> FD_SpecificIdentificationExtDataSet { get; set; }
        public DbSet<FD_SettleReceiptODataEntity> FD_SettleReceiptDataSet { get; set; }
        public DbSet<FD_SettleReceiptDetailODataEntity> FD_SettleReceiptDetailDataSet { get; set; }
        public DbSet<FD_SettleReceiptExtODataEntity> FD_SettleReceiptExtDataSet { get; set; }
        public DbSet<FD_SettleReceiptEntity> FD_SettleReceiptNewDataSet { get; set; }
        public DbSet<FD_SettleReceiptSubjectDetailODataEntity> FD_SettleReceiptSubjectDetailDataSet { get; set; }
        public DbSet<FD_SettleReceiptDetailEntity> FD_SettleReceiptDetailNewDataSet { get; set; }
        public DbSet<FD_SettleReceiptHeadExtend> FD_SettleReceiptHeadExtendDataSet { get; set; }
        public DbSet<VoucherHandleInfoEntity> VoucherHandleInfoEntityDataSet { get; set; }
        public DbSet<Number> GetNumbers { get; set; }
        public DbSet<BalanceSheet> GetBalanceSheetReview { get; set; }
        public DbSet<KMData> GetKMData { get; set; }
        public DbSet<DropODataEntity> DropODataSet { get; set; }
        public DbSet<HrInfo> HrInfoDataSet { get; set; }
        #region 结账管理
        public DbSet<FM_AccoCheckODataEntity> FM_AccoCheckDataSet { get; set; }
        public DbSet<FM_AccoCheckDetailODataEntity> FM_AccoCheckDetailDataSet { get; set; }
        public DbSet<FM_AccoCheckExtendODataEntity> FM_AccoCheckExtendDataSet { get; set; }
        public DbSet<FM_AccoCheckRuleODataEntity> FM_AccoCheckRuleDataSet { get; set; }
        #endregion
        #region 坏账
        public DbSet<FD_IndividualIdentificationODataEntity> FD_IndividualIdentificationDataSet { get; set; }

        public DbSet<FD_IndividualIdentificationDetailODataEntity> FD_IndividualIdentificationDetailDataSet { get; set; }

        public DbSet<FD_IndividualIdentificationExtODataEntity> FD_IndividualIdentificationExtDataSet { get; set; }

        public DbSet<FD_BaddebtAccrualODataEntity> FD_BaddebtAccrualDataSet { get; set; }

        public DbSet<FD_BaddebtAccrualDetailODataEntity> FD_BaddebtAccrualDetailDataSet { get; set; }

        public DbSet<FD_BaddebtAccrualExtODataEntity> FD_BaddebtAccrualExtDataSet { get; set; }

        public DbSet<AgingintervalDataODataEntity> AgingintervalDataDataSet { get; set; }

        public DbSet<FD_IdentificationTypeSubjectODataEntity> FD_IdentificationTypeSubjectDataSet { get; set; }

        public DbSet<FD_IdentificationTypeODataEntity> FD_IdentificationTypeDataSet { get; set; }
        public DbSet<FD_IdentificationTypeAndSubjectODataEntity> FD_IdentificationTypeAndSubjectDataSet { get; set; }

        public DbSet<Biz_CustomerODataEntity> Biz_CustomerDataSet { get; set; }
        public DbSet<FD_BaddebtWriteOffODataEntity> FD_BaddebtWriteOffDataSet { get; set; }

        public DbSet<FD_BaddebtWriteOffDetailODataEntity> FD_BaddebtWriteOffDetailDataSet { get; set; }
        public DbSet<FD_BaddebtRecoveryODataEntity> FD_BaddebtRecoveryDataSet { get; set; }
        public DbSet<FD_BaddebtRecoveryDetailODataEntity> FD_BaddebtRecoveryDetailDataSet { get; set; }

        #endregion

        #region 成本计算设置
        public DbSet<FM_CostParamsSetEntity> FM_CostParamsSet { get; set; }
        public DbSet<FM_CostParamsSetDetailEntity> FM_CostParamsSetDetailSet { get; set; }
        public DbSet<FM_CostParamsSetExtendEntity> FM_CostParamsSetExtendSet { get; set; }
        #endregion

        #region 费用项目设置
        public DbSet<FM_CostProjectEntity> FM_CostProjectSet { get; set; }
        public DbSet<FM_CostProjectDetailEntity> FM_CostProjectDetailSet { get; set; }
        public DbSet<FmCostprojectExtendEntity> FM_CostProjectExtendSet { get; set; }

        public DbSet<FM_CostProjectValidateEntity> FM_CostProjectValidateSet { get; set; }

        public DbSet<FM_EnterpriseEntity> FM_EnterpriseSet { get; set; }
        #endregion

        #region 固定资产
        public DbSet<FA_MarketSubjectODataEntity> FA_MarketSubjectDataSet { get; set; }
        public DbSet<FA_MarketSubjectDetailODataEntity> FA_MarketSubjectDetailDataSet { get; set; }

        public DbSet<FA_PurchaseSettingsODataEntity> FA_PurchaseSettingsDataSet { get; set; }
        public DbSet<FA_PurchaseSettingsDetailODataEntity> FA_PurchaseSettingsDetailDataSet { get; set; }
        public DbSet<FA_AssetsApplyODataEntity> FA_AssetsApplyDataSet { get; set; }
        public DbSet<FA_AssetsApplyListODataEntity> FA_AssetsApplyListDataSet { get; set; }
        public DbSet<FA_AssetsApplyMobileListODataEntity> FA_AssetsApplyMobileListDataSet { get; set; }
        public DbSet<FA_AssetsApplyMobileByInspectListODataEntity> FA_AssetsApplyMobileByInspecListDataSet { get; set; }
        public DbSet<FA_AssetsApplyDetailODataEntity> FA_AssetsApplyDetailDataSet { get; set; }
        public DbSet<FA_AssetsContractODataEntity> FA_AssetsContractDataSet { get; set; }
        public DbSet<FA_AssetsContractListODataEntity> FA_AssetsContractListDataSet { get; set; }
        public DbSet<FA_AssetsContractDetailODataEntity> FA_AssetsContractDetailDataSet { get; set; }
        public DbSet<FA_AssetsContractMobileListODataEntity> FA_AssetsContractMobileListDataSet { get; set; }

        public DbSet<FA_AssetsClassificationODataEntity> FA_AssetsClassificationDataSet { get; set; }
        public DbSet<FA_UseStateTransferODataEntity> FA_UseStateTransferDataSet { get; set; }
        public DbSet<FA_UseStateTransferDetailODataEntity> FA_UseStateTransferDetailDataSet { get; set; }
        //public DbSet<FA_UseStateTransferListODataEntity> FA_UseStateTransferListDataSet { get; set; }

        public DbSet<FA_AssetsMaintainODataEntity> FA_AssetsMaintainDataSet { get; set; }
        public DbSet<FA_AssetsMaintainListODataEntity> FA_AssetsMaintainListDataSet { get; set; }
        public DbSet<FA_AssetsMaintainDetailODataEntity> FA_AssetsMaintainDetailDataSet { get; set; }

        public DbSet<FA_AssetsInspectODataEntity> FA_AssetsInspectDataSet { get; set; }
        public DbSet<FA_AssetsInspectListODataEntity> FA_AssetsInspectListDataSet { get; set; }
        public DbSet<FA_AssetsInspectDetailODataEntity> FA_AssetsInspectDetailDataSet { get; set; }

        public DbSet<FA_PigAssetsResetODataEntity> FA_PigAssetsResetDataSet { get; set; }
        public DbSet<FA_PigAssetsResetListODataEntity> FA_PigAssetsResetListDataSet { get; set; }
        public DbSet<FA_PigAssetsResetDetailODataEntity> FA_PigAssetsResetDetailDataSet { get; set; }
        public DbSet<FA_AssetsInspectMobileODataEntity> FA_AssetsInspectMobileDataSet { get; set; }
        public DbSet<FA_AssetsCardMobileODataEntity> FA_AssetsCardMobileDataSet { get; set; }

        public DbSet<FA_PigAssetsAccrualODataEntity> FA_PigAssetsAccrualDataSet { get; set; }
        public DbSet<FA_PigAssetsAccrualListODataEntity> FA_PigAssetsAccrualListDataSet { get; set; }
        public DbSet<FA_PigAssetsAccrualDetailODataEntity> FA_PigAssetsAccrualDetailDataSet { get; set; }
        public DbSet<FA_PigAssetsResetByAccrualODataEntity> FA_PigAssetsResetByAccrualDataSet { get; set; }

        public DbSet<FA_InventoryODataEntity> FA_InventoryEntityODataSet { get; set; }
        public DbSet<FA_InventoryDetailODataEntity> FA_InventoryDetailEntityODataSet { get; set; }
        #endregion

        #region 种猪资产原值
        public DbSet<FM_PigOriginalAssetsEntity> FM_PigOriginalAssetsSet { get; set; }
        public DbSet<FM_PigOriginalAssetsdetailEntity> FM_PigOriginalAssetsDetailSet { get; set; }
        public DbSet<FM_PigOriginalAssetsdetaillistEntity> FM_PigOriginalAssetsDetailListSet { get; set; }
        #endregion

        #region 费用填报
        public DbSet<FM_ExpensereportEntity> FM_ExpensereportSet { get; set; }
        public DbSet<fm_expensereportdetailEntity> fm_expensereportdetailSet { get; set; }
        public DbSet<fm_expensereportdetaillogEntity> fm_expensereportdetaillogSet { get; set; }
        public DbSet<fm_expensereportextendEntity> fm_expensereportextendSet { get; set; }
        public DbSet<fm_expensereportextendlistEntity> fm_expensereportextendlistSet { get; set; }
        public DbSet<FM_ExpenseCalEntity> FM_ExpenseCalSet { get; set; }
        public DbSet<FM_PigGroupDataEntity> FM_PigGroupDataSet { get; set; }
        public DbSet<FM_ExpenseSummaryReportEntity> FM_ExpenseSummaryReportSet { get; set; }
        public DbSet<FM_ExpenseReportLogsEntity> FM_ExpenseReportLogsSet { get; set; }
        public DbSet<FM_ExpenseReportDetailLogsEntity> FM_ExpenseReportDetailLogsSet { get; set; }
        #endregion

        #region 申请
        public DbSet<FD_ExpenseODataEntity> FD_ExpenseDataSet { get; set; }
        public DbSet<FD_ExpenseDetailODataEntity> FD_ExpenseDetailDataSet { get; set; }
        public DbSet<FD_ExpenseExtODataEntity> FD_ExpenseExtDataSet { get; set; }
        public DbSet<RelatedODataEntity> RelatedDataSet { get; set; }
        #endregion

        #region 资金归集
        public DbSet<FM_CashSweepODataEntity> FM_CashSweepEntityODataSet { get; set; }
        public DbSet<FM_CashSweepDetailODataEntity> FM_CashSweepDetailEntityODataSet { get; set; }
        public DbSet<FD_PayextendODataEntity> FD_PayextendODataEntity { get; set; }
        public DbSet<RevolvingFundDetailODataEntity> RevolvingFundDetailODataEntity { get; set; }
        public DbSet<FM_CashSweepSettingODataEntity> FM_CashSweepSettingODataSet { get; set; }
        public DbSet<FM_CashSweepSettingDetailODataEntity> FM_CashSweepSettingDetailODataSet { get; set; }
        public DbSet<FM_CashSweepSettingExtODataEntity> FM_CashSweepSettingExtODataSet { get; set; }
        #endregion
        public DbSet<RelatedList> RelatedListEntityDataSet { get; set; }
        public DbSet<SaSalseUnionReceivables> SaSalseUnionReceivablesDataSet { get; set; }
        public DbSet<FundReceivablesData> FundReceivablesDataDataSet { get; set; }
        public DbSet<FundReceivablesCusData> FundReceivablesCusDataDataSet { get; set; }
        public DbSet<PayResultCount> PayResultCountDataSet { get; set; }
        public DbSet<TemplateDataDrop> TemplateDataDropDataSet { get; set; }
        public DbSet<TemplateData> TemplateDataSet { get; set; }
        public DbSet<BankInfoCount> BankInfoCountDataSet { get; set; }
        public DbSet<CashSweepInfo> CashSweepInfoDataSet { get; set; }
        public DbSet<RefundList> RefundListDataSet { get; set; }
        public DbSet<OptionInfo> OptionInfoDataSet { get; set; }
        public DbSet<TemplateEnterData> TemplateEnterDataSet { get; set; }
        public DbSet<FD_PaymentReceivablesEntity> FD_PaymentReceivablesEntityDataSet { get; set; }
        public DbSet<FD_ReceivablesEntity> FD_ReceivablesEntityDataSet { get; set; }
        
        public DbSet<NumericalOrderData> NumericalOrderDataSet { get; set; }
        public DbSet<NumericalOrderVoucherData> NumericalOrderVoucherDataSet { get; set; }
        public DbSet<FD_PaymentReceivablesHeadEntity> FD_PaymentReceivablesHeadEntityDataSet { get; set; }
        public DbSet<ReviewFlowPath> ReviewFlowPathDataSet { get; set; }
        public DbSet<FD_PaymentReceivablesMobileEntity> FD_PaymentReceivablesMobileEntityDataSet { get; set; }
        public DbSet<ReceiptAmout> ReceiptAmoutDataSet { get; set; }
        public DbSet<FD_PaymentReceivablesDetailEntity> FD_PaymentReceivablesDetailEntityDataSet { get; set; }
        public DbSet<FD_ReceivablesDetailEntity> FD_ReceivablesDetailEntityDataSet { get; set; }
        public DbSet<FD_PaymentExtendEntity> FD_PaymentExtendEntityDataSet { get; set; }
        public DbSet<RecheckPaymentList> RecheckPaymentListEntityDataSet { get; set; }
        public DbSet<PaymentList> PaymentListEntityDataSet { get; set; }
        public DbSet<PaymentOpenList> PaymentOpenListEntityDataSet { get; set; }
        public DbSet<FD_PaymentExtendSummaryEntity> FD_PaymentExtendSummaryEntityDataSet { get; set; }
        public DbSet<FD_PaymentExtendSummaryEntityByAmount> FD_PaymentExtendSummaryEntityByAmountDataSet { get; set; }
        public DbSet<FD_PaymentReceivablesSummaryDetailEntity> FD_PaymentReceivablesSummaryDetailEntityDataSet { get; set; }
        public DbSet<Enterprise> EnterpriseEntityDataSet { get; set; }
        public DbSet<ApprovalSetDetail> ApprovalSetDetailDataSet { get; set; }
        public DbSet<FD_AccountAODataEntity> FD_AccountADataSet { get; set; }
        public DbSet<Nxin_DigitalIntelligenceMapODataEntity> Nxin_DigitalIntelligenceMapDataSet { get; set; }
        public DbSet<ApplyData> ApplyDataDbSet { get; set; }
        public DbSet<BankReceivablesEntity> BankReceivablesEntityDbSet { get; set; }
        public DbSet<BankAccountInfo> BankAccountInfoDbSet { get; set; }
        public DbSet<BIZ_RelatedODataEntity> BIZ_RelatedDataSet { get; set; }
        public DbSet<biz_relateddetail> biz_relateddetail { get; set; }
        public DbSet<fd_scheduleset> fd_scheduleset { get; set; }
        public DbSet<fd_scheduleplanEntity> fd_scheduleplanDataSet { get; set; }
        public DbSet<fd_scheduleplanReportEntity> fd_scheduleplanReportDataSet { get; set; }
        public DbSet<MenuInfo> MeunInfoDataSet { get; set; }
        public DbSet<ApplyRelation> ApplyRelationDataSet { get; set; }
        public DbSet<fd_scheduleplan> fd_scheduleplan { get; set; }
        #region  绩效
        public DbSet<PerformanceIncomeEntity> PerformanceIncomeEntityDataSet { get; set; }
        public DbSet<FM_PerformanceIncomeEntity> FM_PerformanceIncomeEntityDataSet { get; set; }
        #endregion
        public DbSet<SalesSummaryEntity> SalesSummaryEntitiesDataSet { get; set; }
        public DbSet<SalesFinanceEntity> SalesFinanceEntityDataSet { get; set; }
        public DbSet<SortInfo> SortInfoDataSet { get; set; }
        public DbSet<CustomreService> CustomreServiceDataSet { get; set; }
        public DbSet<ServicePersonSort> ServicePersonSortDataSet { get; set; }
        public DbSet<PerformanceSet> PerformanceSetDataSet { get; set; }
        public DbSet<fd_auxiliaryproject> fd_auxiliaryprojectDataSet { get; set; }
        public DbSet<fd_auxiliarytype> fd_auxiliarytypeDataSet { get; set; }

        #region 波尔莱特 定制化 部门利润表查询
        public DbSet<CostData> CostDataSet { get; set; }
        public DbSet<SalesSummary> SalesSummaryDataSet { get; set; }
        public DbSet<MS_FormulaODataEntity> MS_FormulaDataSet { get; set; }
        public DbSet<MS_FormulaListODataEntity> MS_FormulaListDataList { get; set; }
        public DbSet<MS_FormulaDetailODataEntity> MS_FormulaDetailDataSet { get; set; }
        public DbSet<MS_FormulaExtendODataEntity> MS_FormulaExtendDataSet { get; set; }
        public DbSet<MS_FormulaExprotODataEntity> MS_FormulaExprotDataSet { get; set; }

        



        #endregion
        #region 营销商品成本设定

        public DbSet<FD_MarketingProductCostSettingListQueryModel> FD_MarketingProductCostSettingListQueryModel { get; set; }

        public DbSet<FD_MarketingProductCostSettingQueryModel> FD_MarketingProductCostSettingQueryModel { get; set; }

        public DbSet<SalesSummaryCostInfoQueryModel> SalesSummaryCostInfoQueryModel { get; set; }

        #endregion

        #region 总账报表
        public DbSet<AssistRecordResultEntity> AssistRecordDataSet { get; set; }
        public DbSet<AssistRecordSummaryResultEntity> AssistRecordSummaryDataSet { get; set; }
        #endregion

        #region 配方商品价格设定
        public DbSet<MS_FormulaProductPriceODataEntity> MS_FormulaProductPriceDataSet { get; set; }
        public DbSet<MS_FormulaProductPriceDetailODataEntity> MS_FormulaProductPriceDetailDataSet { get; set; }
        public DbSet<MS_FormulaProductPriceExtODataEntity> MS_FormulaProductPriceExtDataSet { get; set; }
        public DbSet<MS_FormulaProductPriceValidODataEntity> MS_FormulaProductPriceValaidDataSet { get; set; }
        public DbSet<MS_FormulaProductPriceExportODataEntity> MS_FormulaProductPriceExportDataSet { get; set; }
        #endregion
        public QlwCrossDbContext(DbContextOptions<QlwCrossDbContext> options)
        : base(options)
        {

        }
        protected override void OnModelCreating(ModelBuilder modelBuilder)
        {
            modelBuilder.ApplyConfiguration(new FD_AccountTransferConfiguration());

            modelBuilder.Entity<FD_MarketingProductCostSettingQueryModel>().HasNoKey();
            modelBuilder.Entity<SalesSummaryCostInfoQueryModel>().HasNoKey();
        }
        /// <summary>
        /// 使用反射追加属性并设置值
        /// </summary>
        /// <param name="obj"></param>
        /// <param name="propertyName"></param>
        /// <param name="value"></param>
        public void AddProperty(object obj, string propertyName, object value)
        {
            var expandoObj = (ExpandoObject)obj;
            var expandoDict = (IDictionary<string, object>)expandoObj;
            // 属性类型处理
            if (value is long || value is ulong)
            {
                value = value.ToString();
            }
            else if(value is DBNull)
            {
                value = "";
            }else if(value is DateTime)
            {
                value = Convert.ToDateTime(value).ToString("yyyy-MM-dd hh:mm:ss");
            }else if(value is decimal)
            {
                value = Convert.ToDouble(value);
            }
            // 使用 ExpandoObject 的动态性质添加属性
            expandoDict[propertyName] = value;
        }
        /// <summary>
        /// 使用反射给 dynamic 对象的属性赋值
        /// </summary>
        /// <param name="obj"></param>
        /// <param name="propertyName"></param>
        /// <param name="value"></param>
        public void SetProperty(dynamic obj, string propertyName, object value)
        {
            var expandoDict = (IDictionary<string, object>)obj;
            if (expandoDict.ContainsKey(propertyName))
            {
                expandoDict[propertyName] = value;
            }
            else
            {
                expandoDict.Add(propertyName, value);
            }
        }
        /// <summary>
        /// 防SQL 注入 参数过滤
        /// </summary>
        /// <param name="str"></param>
        /// <returns></returns>
        public static string ReplaceSQLChar(string str)
        {
            if (str == String.Empty)
                return String.Empty;
            str = str.Replace("'", "");
            str = str.Replace(";", "");
            str = str.Replace(",", "");
            str = str.Replace("?", "");
            str = str.Replace("<", "");
            str = str.Replace(">", "");
            str = str.Replace("(", "");
            str = str.Replace(")", "");
            str = str.Replace("@", "");
            str = str.Replace("=", "");
            str = str.Replace("+", "");
            str = str.Replace("*", "");
            str = str.Replace("&", "");
            str = str.Replace("#", "");
            str = str.Replace("%", "");
            str = str.Replace("$", "");

            //删除与数据库相关的词
            str = Regex.Replace(str, "select", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "insert", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "delete from", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "count", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "drop table", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "truncate", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "asc", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "mid", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "char", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "xp_cmdshell", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "exec master", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "net localgroup administrators", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "and", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "net user", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "or", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "net", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "-", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "delete", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "drop", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "script", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "update", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "and", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "chr", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "master", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "truncate", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "declare", "", RegexOptions.IgnoreCase);
            str = Regex.Replace(str, "mid", "", RegexOptions.IgnoreCase);
            return str;
        }
        /// <summary>
        /// SQL直接查询出结果
        /// 取值示例 调试可用
        /// var r = results.Where(m => m.xxxx.ToString() == "xxxxxx").ToList();
        /// </summary>
        /// <param name="sql">SQL语句</param>
        /// <returns></returns>
        public List<dynamic> DynamicSqlQuery(string sql)
        {
            List<dynamic> results = new List<dynamic>();
            using (var command = this.Database.GetDbConnection().CreateCommand())
            {
                command.CommandText = sql;
                command.CommandType = CommandType.Text;

                this.Database.OpenConnection();

                using (var reader = command.ExecuteReader())
                {
                    while (reader.Read())
                    {
                        dynamic record = new ExpandoObject();
                        for (int i = 0; i < reader.FieldCount; i++)
                        {
                            var fieldName = reader.GetName(i);
                            try
                            {
                                var fieldValue = reader.GetValue(i);
                                AddProperty(record, fieldName, fieldValue);
                            }
                            catch (Exception ex)
                            {

                                throw new ErroException($@"列名{fieldName},需要被转换 异常信息："+ex.Message);
                            }
                        }
                        results.Add(record);
                    }
                }
            }
            return results;
        }
        public class ErroException : Exception
        {
            public ErroException(string message) : base(message)
            {
            }
        }
    }
}
