// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Architecture.Seedwork.Domain;

#nullable disable

namespace FinanceManagement.Domain
{
    public partial class fm_expensereportextendlist : EntityBase
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(TypeName = "int(11)")]
        public int RecordID { get; set; }
        /// <summary>
        /// 关联明细ID
        /// </summary>
        [Column(TypeName = "int(11)")]
        public int DetailID { get; set; }
        /// <summary>
        /// 猪场ID
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string PigFarmID { get; set; }
        /// <summary>
        /// 部门ID
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string DeptOrOthersID { get; set; }
        ///// <summary>
        ///// 分摊方式
        ///// </summary>
        //[Column(TypeName = "bigint(20)")]
        //public string AllocationType { get; set; }
        /// <summary>
        /// 分摊值
        /// </summary>
        public decimal ExpenseValue { get; set; }
        /// <summary>
        /// 费用金额
        /// </summary>
        public decimal ExpenseAmount { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(1024)]
        public string Remarks { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        [Column(TypeName = "timestamp")]
        public DateTime ModifiedDate { get; set; }
    }
}