// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Architecture.Seedwork.Domain;

#nullable disable

namespace FinanceManagement.Domain
{
    public partial class fm_expensereportdetail : EntityBase
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(TypeName = "int(11)")]
        public int RecordID { get; set; }
        /// <summary>
        /// 流水号
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 费用项目ID
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string CostProjectID { get; set; }
        /// <summary>
        /// 归集类型
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string CollectionType { get; set; }
        /// <summary>
        /// 取数来源
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string DataSource { get; set; }
        /// <summary>
        /// 分摊方式
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string AllocationType { get; set; }
        /// <summary>
        /// 费用金额
        /// </summary>
        public decimal ExpenseAmount { get; set; }

        /// <summary>
        /// 是否归集
        /// </summary>
        [Column(TypeName = "int(1)")]
        public int IsCollect { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        [Column(TypeName = "timestamp")]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// 取数集合
        /// </summary>
        public List<fm_expensereportextend> ExtendList { get; set; } = new List<fm_expensereportextend>();

        /// <summary>
        /// 归集明细集合
        /// </summary>
        public List<fm_expensereportextendlist> ExtendDetailList { get; set; } = new List<fm_expensereportextendlist>();

        /// <summary>
        /// 取数日志集合
        /// </summary>
        public List<fm_expensereportdetaillog> DetailLogList { get; set; } = new List<fm_expensereportdetaillog>();
    }
}