// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Architecture.Seedwork.Domain;

#nullable disable

namespace FinanceManagement.Domain
{
    public partial class fm_expensereportdetaillog : EntityBase
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        [Column(TypeName = "int(11)")]
        public int RecordID { get; set; }
        /// <summary>
        /// 关联明细ID
        /// </summary>
        [Column(TypeName = "int(11)")]
        public int DetailID { get; set; }
        /// <summary>
        /// 辅助项
        /// </summary>
        [StringLength(100)]
        public string SubsidiaryOption { get; set; }
        /// <summary>
        /// 金额
        /// </summary>
        public decimal OccuredAmount { get; set; }
        /// <summary>
        /// 错误编码
        /// </summary>
        [StringLength(10)]
        public string ErrorCode { get; set; }
        /// <summary>
        /// 错误信息
        /// </summary>
        [StringLength(1024)]
        public string ErrorMsg { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        [Column(TypeName = "timestamp")]
        public DateTime ModifiedDate { get; set; }
    }
}