// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using Architecture.Seedwork.Domain;
#nullable disable

namespace FinanceManagement.Domain
{
    public partial class fm_expensereport : EntityBase
    {
        /// <summary>
        /// 流水号
        /// </summary>
        [Key]
        [Column(TypeName = "bigint(20)")]
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 日期
        /// </summary>
        [Column(TypeName = "date")]
        public DateTime DataDate { get; set; }
        /// <summary>
        /// 填报期间
        /// </summary>
        //[Required]
        [StringLength(10)]
        public string ReportPeriod { get; set; }
        /// <summary>
        /// 单位ID
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string EnterpriseID { get; set; }
        /// <summary>
        /// 费用总金额
        /// </summary>
        public decimal? ExpenseAmount { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        [StringLength(1024)]
        public string Remarks { get; set; }
        /// <summary>
        /// 制单人ID
        /// </summary>
        [Column(TypeName = "bigint(20)")]
        public string OwnerID { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        [Column(TypeName = "datetime")]
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        [Column(TypeName = "timestamp")]
        public DateTime ModifiedDate { get; set; }

        /// <summary>
        /// 明细集合
        /// </summary>
        public List<fm_expensereportdetail> DetailList { get; set; } = new List<fm_expensereportdetail>();
    }
}