// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace FinanceManagement.Domain
{
    /// <summary>
    /// 成本计算设置主表
    /// </summary>
    public partial class FmCostparamsset : EntityBase
    {
        /// <summary>
        /// 流水号
        /// </summary>
        [Key]
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 单位ID
        /// </summary>
        public string EnterpriseId { get; set; }
        /// <summary>
        /// 卡片生成方式
        /// </summary>
        public string GenerationMode { get; set; }
        /// <summary>
        /// 总折旧月数
        /// </summary>
        public int TotalDepreciationMonths { get; set; }
        /// <summary>
        /// 残值计算方法
        /// </summary>
        public string ResidualValueCalMethod { get; set; }
        /// <summary>
        /// 残值率(%)
        /// </summary>
        public decimal? ResidualValueRate { get; set; }
        /// <summary>
        /// 固定残值
        /// </summary>
        public decimal? ResidualValue { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 制单人ID
        /// </summary>
        public string OwnerId { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        public DateTime ModifiedDate { get; set; }
    }
}