// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace FinanceManagement.Domain
{
    /// <summary>
    /// 成本计算设置扩展表
    /// </summary>
    public partial class FmCostparamssetextend : EntityBase
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RecordId { get; set; }
        /// <summary>
        /// 流水号
        /// </summary>
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 扩展类型ID（生成方式/总折旧月数）
        /// </summary>
        public string ExtendTypeId { get; set; }
        /// <summary>
        /// 来源类型ID
        /// </summary>
        public string SourceTypeId { get; set; }
        /// <summary>
        /// 生成方式/获取方式
        /// </summary>
        public string CreatedTypeId { get; set; }
        /// <summary>
        /// 总折旧月数
        /// </summary>
        public int TotalDepreciationMonths { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        public DateTime ModifiedDate { get; set; }
    }
}