// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

#nullable disable

namespace FinanceManagement.Domain
{
    /// <summary>
    /// 成本计算设置明细表
    /// </summary>
    public partial class FmCostparamssetdetail : EntityBase
    {
        /// <summary>
        /// 主键
        /// </summary>
        [Key, DatabaseGenerated(DatabaseGeneratedOption.Identity)]
        public int RecordId { get; set; }
        /// <summary>
        /// 流水号
        /// </summary>
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 猪场ID
        /// </summary>
        public string PigFarmId { get; set; }
        /// <summary>
        /// 猪场建账期间
        /// </summary>
        public string BeginPeriod { get; set; }
        /// <summary>
        /// 猪场建账日期
        /// </summary>
        public DateTime BeginDate { get; set; }
        /// <summary>
        /// 成本启用期间
        /// </summary>
        public string EnablePeriod { get; set; }
        /// <summary>
        /// 成本计算开始日期
        /// </summary>
        public DateTime EnableDate { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        public DateTime ModifiedDate { get; set; }
    }
}