// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Microsoft.EntityFrameworkCore.Metadata.Builders;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore;
using System; 
using FinanceManagement.Domain;

#nullable disable

namespace FinanceManagement.Infrastructure.EntityConfigurations
{
    public partial class Biz_ReviewConfiguration : IEntityTypeConfiguration<Biz_Review>
    {
        public void Configure(EntityTypeBuilder<Biz_Review> entity)
        {
            entity.HasKey(e => e.RecordID)
                .HasName("PRIMARY");

            entity.ToTable("biz_reviwe");

            entity.HasComment("审核表");

            entity.HasIndex(e => e.NumericalOrder)
                .HasName("NumericalOrder");

            entity.HasIndex(e => e.ReviweType)
                .HasName("idx_ReviweType");

            entity.Property(e => e.RecordID)
                .HasColumnType("int(11)")
                .HasComment("主键ID");

            entity.Property(e => e.CheckMark)
                .HasColumnType("int(3)")
                .HasDefaultValueSql("'0'")
                .HasComment("审核标识值");

            entity.Property(e => e.CheckedByID)
                .HasColumnType("bigint(20)")
                .HasComment("审核人ID").AddStringToLongConvert();

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建日期");

            entity.Property(e => e.Guid)
                .HasComment("全球唯一关键字")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.Level)
                .HasColumnType("bigint(20)")
                .HasComment("级别/级次");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .ValueGeneratedOnAddOrUpdate();

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .HasComment("流水号")
                .AddStringToLongConvert();

            entity.Property(e => e.ReviweType)
                .HasColumnType("bigint(20)")
                .HasComment("类型（菜单ID)")
                .AddStringToLongConvert();

            OnConfigurePartial(entity);
        }

        partial void OnConfigurePartial(EntityTypeBuilder<Biz_Review> entity);
    }
}
