// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class biz_datadictConfiguration : IEntityTypeConfiguration<biz_datadict>
    {
        public void Configure(EntityTypeBuilder<biz_datadict> entity)
        {
            entity.HasKey(e => e.DataDictID)
                .HasName("PRIMARY");

            entity.HasComment("字典冗余表");

            entity.Property(e => e.DataDictID)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("字典ID");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建日期");

            entity.Property(e => e.DataDictName)
                .IsRequired()
                .HasColumnType("varchar(200)")
                .HasComment("名称")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.DataDictType)
                .HasColumnType("varchar(200)")
                .HasComment("字典类型")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.EnterpriseID)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("集团ID");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("最后修改日期")
                .ValueGeneratedOnAddOrUpdate();

            entity.Property(e => e.PID)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("父级ID");
        }
    }
}
