// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class bsfileConfiguration : IEntityTypeConfiguration<bsfile>
    {
        public void Configure(EntityTypeBuilder<bsfile> entity)
        {
            entity.HasKey(e => e.RecordID)
                .HasName("PRIMARY");

            entity.HasComment("文件/附件表");

            entity.HasIndex(e => e.NumericalOrder)
                .HasName("Idx_NumericalOrder");

            entity.Property(e => e.RecordID)
                .HasColumnType("int(11)")
                .HasComment("标识列");

            entity.Property(e => e.CreationDate)
                .HasColumnType("datetime")
                .HasComment("创建日期");

            entity.Property(e => e.EnterId)
                .HasColumnType("bigint(20)")
                .HasComment("单位ID")
                .AddStringToLongConvert();

            entity.Property(e => e.FileName)
                .IsRequired()
                .HasColumnType("varchar(128)")
                .HasComment("文件名")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.FilePath)
                .IsRequired()
                .HasColumnType("varchar(128)")
                .HasComment("文件路径")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.FileType)
                .HasColumnType("bigint(20)")
                .HasComment("应用ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Guid)
                .HasComment("全球唯一关键字")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("修改日期")
                .ValueGeneratedOnAddOrUpdate();

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .HasComment("关联流水号")
                .AddStringToLongConvert();

            entity.Property(e => e.OwnerID)
                .HasColumnType("bigint(20)")
                .HasComment("操作员ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Remarks)
                .HasColumnType("varchar(1024)")
                .HasComment("备注")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.Type)
                .HasColumnType("int(3)")
                .HasDefaultValueSql("'2'")
                .HasComment("类型（1/照片，2/其他）");
        }
    }
}
