// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class fd_auxiliarytypeConfiguration : IEntityTypeConfiguration<fd_auxiliarytype>
    {
        public void Configure(EntityTypeBuilder<fd_auxiliarytype> entity)
        {
            entity.HasKey(e => e.NumericalOrder)
                .HasName("PRIMARY");

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("流水号");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建日期");

            entity.Property(e => e.GroupId)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("集团Id");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("最后修改日期");

            entity.Property(e => e.OwnerID)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("制单人");

            entity.Property(e => e.Remarks)
                .HasColumnType("varchar(1024)")
                .HasComment("备注")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.TypeCode)
                .HasColumnType("varchar(255)")
                .HasDefaultValueSql("'01'")
                .HasComment("类型编码")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.TypeName)
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasComment("类型名称")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.TypeTag)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("类型标签");

            entity.Property(e => e.IsCom)
                .HasColumnType("bit(1)");
        }
    }
}
