// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class fd_auxiliaryprojectConfiguration : IEntityTypeConfiguration<fd_auxiliaryproject>
    {
        public void Configure(EntityTypeBuilder<fd_auxiliaryproject> entity)
        {
            entity.HasKey(e => e.ProjectId)
                .HasName("PRIMARY");

            entity.Property(e => e.ProjectId)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("项目ID");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建日期");

            entity.Property(e => e.GroupId)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("集团Id");

            entity.Property(e => e.Level)
                .HasColumnType("bigint(20)")
                .HasComment("级次");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("最后修改日期");

            entity.Property(e => e.OwnerID)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("制单人");

            entity.Property(e => e.Pid)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("父级Id");

            entity.Property(e => e.ProjectCode)
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasComment("项目代码")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.ProjectName)
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasComment("项目名称")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.ProjectType)
                .HasColumnType("bigint(20)")
                .AddStringToLongConvert()
                .HasComment("项目类型");

            entity.Property(e => e.Remarks)
                .HasColumnType("varchar(1024)")
                .HasDefaultValueSql("''")
                .HasComment("备注")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.IsUse)
                .HasColumnType("bit(1)");
        }
    }
}
