// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class fd_paymentreceivablesvoucherConfiguration : IEntityTypeConfiguration<fd_paymentreceivablesvoucher>
    {
        public void Configure(EntityTypeBuilder<fd_paymentreceivablesvoucher> entity)
        {
            entity.HasKey(e => e.NumericalOrder)
                .HasName("PRIMARY");

            entity.HasComment("集中收付扩展存储表头");

            entity.HasIndex(e => e.DataDate)
                .HasName("idx_DataDate");

            entity.HasIndex(e => e.EnterpriseID)
                .HasName("idx_EnterpriseID");

            entity.HasIndex(e => e.Guid)
                .HasName("idx_Guid");

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .HasComment("流水号")
                .AddStringToLongConvert()
                ;

            entity.Property(e => e.AccountNo)
                .HasColumnType("varchar(128)")
                .HasComment("记账号")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.AttachmentNum)
                .HasColumnType("varchar(128)")
                .HasComment("附件数")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasComment("创建日期");

            entity.Property(e => e.DataDate)
                .HasColumnType("date")
                .HasComment("单据日期");

            entity.Property(e => e.EnterpriseID)
                .HasColumnType("bigint(20)")
                .HasComment("单位ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Guid)
                .HasComment("全球唯一关键字")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("修改日期")
                .ValueGeneratedOnAddOrUpdate();

            entity.Property(e => e.Number)
                .HasColumnType("bigint(20)")
                .HasComment("凭证号")
                .AddStringToLongConvert();

            entity.Property(e => e.OwnerID)
                .HasColumnType("bigint(20)")
                .HasComment("制单人ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Remarks)
                .HasColumnType("varchar(1024)")
                .HasDefaultValueSql("''")
                .HasComment("说明/备注")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.SettleReceipType)
                .HasColumnType("bigint(20)")
                .HasComment("类型（字典）")
                .AddStringToLongConvert();

            entity.Property(e => e.TicketedPointID)
                .HasColumnType("bigint(20)")
                .HasComment("字号（开票点）")
                .AddStringToLongConvert();
        }
    }
}
