// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class FD_PaymentReceivablesDetailConfiguration : IEntityTypeConfiguration<FD_PaymentReceivablesDetail>
    {
        public void Configure(EntityTypeBuilder<FD_PaymentReceivablesDetail> entity)
        {
            entity.HasKey(e => e.RecordID)
                .HasName("PRIMARY");

            entity.HasComment("收付款明细");

            entity.HasIndex(e => e.CustomerID)
                .HasName("idx_CustomerID");

            entity.HasIndex(e => e.Guid)
                .HasName("idx_Guid");

            entity.HasIndex(e => e.MarketID)
                .HasName("idx_MarketID");

            entity.HasIndex(e => e.NumericalOrder)
                .HasName("FK_Reference_41");

            entity.HasIndex(e => e.PersonID)
                .HasName("idx_PersonID");

            entity.HasIndex(e => e.ReceiptAbstractID)
                .HasName("idx_ReceiptAbstractID");

            entity.Property(e => e.RecordID)
                .HasColumnType("int(11)")
                .HasComment("主键ID");

            entity.Property(e => e.AccountID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("资金账户ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Amount).HasColumnType("decimal(18,2)");

            entity.Property(e => e.AttachCount)
                .HasColumnType("int(3)")
                .HasComment("附件数量");

            entity.Property(e => e.BusinessType)
                .HasColumnType("bigint(20)")
                .HasComment("业务类型（字典表）")
                .AddStringToLongConvert();

            entity.Property(e => e.Charges)
                .HasColumnType("decimal(18,2)")
                .HasDefaultValueSql("'0.00'")
                .HasComment("手续费");

            entity.Property(e => e.Content)
                .HasColumnType("varchar(1024)")
                .HasComment("内容")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.CustomerID)
                .HasColumnType("bigint(20)")
                .HasComment("客户ID")
                .AddStringToLongConvert();

            entity.Property(e => e.EnterpriseID)
                .HasColumnType("bigint(20)")
                .HasComment("所属单位ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Guid)
                .HasComment("全球唯一关键字")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.MarketID)
                .HasColumnType("bigint(20)")
                .HasComment("部门ID")
                .AddStringToLongConvert();

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .HasComment("流水号")
                .AddStringToLongConvert();

            entity.Property(e => e.PaymentTypeID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("付款方式ID（字典表取数）")
                .AddStringToLongConvert();

            entity.Property(e => e.PersonID)
                .HasColumnType("bigint(20)")
                .HasComment("员工ID")
                .AddStringToLongConvert();

            entity.Property(e => e.ReceiptAbstractID)
                .HasColumnType("bigint(20)")
                .HasComment("支出类别")
                .AddStringToLongConvert();


        }
    }
}
