// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class fd_receivablessetConfiguration : IEntityTypeConfiguration<fd_receivablesset>
    {
        public void Configure(EntityTypeBuilder<fd_receivablesset> entity)
        {
            entity.HasKey(e => e.NumericalOrder)
                .HasName("PRIMARY");

            entity.HasComment("收款单设置");

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .HasComment("流水号")
                .AddStringToLongConvert();

            entity.Property(e => e.Content)
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasDefaultValueSql("''")
                .HasComment("收款内容")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.CostAccoSubjectID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("费用科目")
                .AddStringToLongConvert();

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasComment("创建日期");

            entity.Property(e => e.CreditAccoSubjectID)
                .HasColumnType("bigint(20)")
                .HasComment("贷方科目")
                .AddStringToLongConvert();

            entity.Property(e => e.EnterpriseID)
                .HasColumnType("bigint(20)")
                .HasComment("单位ID")
                .AddStringToLongConvert();

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("最后修改日期");

            entity.Property(e => e.OwnerID)
                .HasColumnType("bigint(20)")
                .HasComment("制单人")
                .AddStringToLongConvert();

            entity.Property(e => e.ReceiptAbstractID)
                .HasColumnType("bigint(20)")
                .HasComment("收款摘要")
                .AddStringToLongConvert();

            entity.Property(e => e.Remarks)
                .HasColumnType("varchar(1024)")
                .HasDefaultValueSql("''")
                .HasComment("备注")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.TicketedPointID)
                .HasColumnType("bigint(20)")
                .HasComment("单据字")
                .AddStringToLongConvert();

            entity.Property(e => e.DebitAccoSubjectID)
                .HasColumnType("bigint(20)")
                .HasComment("借方科目")
                .AddStringToLongConvert();

            entity.Property(e => e.PaymentType)
                .HasColumnType("bigint(20)")
                .HasComment("结算方式")
                .AddStringToLongConvert();

            entity.Property(e => e.AccountID)
                .HasColumnType("bigint(20)")
                .HasComment("资金账户")
                .AddStringToLongConvert();

            entity.Property(e => e.AppID)
                .HasColumnType("bigint(20)")
                .HasComment("单据类型（收款/会计凭证） APPID")
                .AddStringToLongConvert();

            entity.Property(e => e.SettleReceipType)
                .HasColumnType("bigint(20)")
                .HasComment("凭证类别")
                .AddStringToLongConvert();

            entity.Property(e => e.TemplateName)
                .IsRequired()
                .HasColumnType("varchar(255)")
                .HasDefaultValueSql("''")
                .HasComment("模板名称")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");
        }
    }
}
