// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class FD_SettleReceiptDetailConfiguration : IEntityTypeConfiguration<FD_SettleReceiptDetail>
    {
        public void Configure(EntityTypeBuilder<FD_SettleReceiptDetail> entity)
        {
            entity.HasKey(e => e.RecordID)
                .HasName("PRIMARY");

            entity.HasComment("凭证明细（表体）");

            entity.HasIndex(e => e.AccoSubjectCode)
                .HasName("idx_AccoSubjectCode");

            entity.HasIndex(e => e.AccountID)
                .HasName("idx_AccountID");

            entity.HasIndex(e => e.CustomerID)
                .HasName("idx_CustomerID");

            entity.HasIndex(e => e.Guid)
                .HasName("idx_Guid");

            entity.HasIndex(e => e.NumericalOrder)
                .HasName("idx_NumericalOrder");

            entity.HasIndex(e => e.OrganizationSortID)
                .HasName("idx_ordId");

            entity.HasIndex(e => e.PersonID)
                .HasName("idx_PersonID");

            entity.HasIndex(e => e.ReceiptAbstractID)
                .HasName("idx_ReceiptAbstractID");

            entity.Property(e => e.RecordID)
                .HasColumnType("int(11)")
                .HasComment("标示列");

            entity.Property(e => e.AccoSubjectCode)
                .HasColumnType("varchar(128)")
                .HasDefaultValueSql("'0'")
                .HasComment("客户ID")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.AccoSubjectID)
                .HasColumnType("bigint(20)")
                .HasComment("科目ID")
                .AddStringToLongConvert();

            entity.Property(e => e.AccountID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("资金账户ID")
                .AddStringToLongConvert();

            entity.Property(e => e.AgingDate)
                .HasColumnType("date")
                .HasComment("账龄日期");

            entity.Property(e => e.Content)
                .HasColumnType("varchar(1024)")
                .HasComment("内容")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.Credit)
                .HasColumnType("decimal(18,2)")
                .HasComment("贷方金额");

            entity.Property(e => e.CustomerID)
                .HasColumnType("bigint(20)")
                .HasComment("客户/供应商ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Debit)
                .HasColumnType("decimal(18,2)")
                .HasComment("借方金额");

            entity.Property(e => e.EnterpriseID)
                .HasColumnType("bigint(20)")
                .HasComment("所属单位ID")
                .AddStringToLongConvert();

            entity.Property(e => e.Guid)
                .HasComment("全球唯一关键字")
                .HasCharSet("utf8")
                .HasCollation("utf8_general_ci");

            entity.Property(e => e.IsCharges)
                .HasColumnType("bit(1)")
                .HasDefaultValueSql("b'0'")
                .HasComment("是否费用");

            entity.Property(e => e.LorR)
                .HasColumnType("bit(1)")
                .HasComment("借贷方（0：借方，1贷方）");

            entity.Property(e => e.MarketID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("部门ID")
                .AddStringToLongConvert();

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .HasComment("流水号")
                .AddStringToLongConvert();

            entity.Property(e => e.OrganizationSortID)
                .HasColumnType("bigint(20)")
                .HasComment("业务单元ID")
                .AddStringToLongConvert();

            entity.Property(e => e.PaymentTypeID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("付款方式ID（字典表取数）")
                .AddStringToLongConvert();

            entity.Property(e => e.PersonID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("人员ID")
                .AddStringToLongConvert();

            entity.Property(e => e.ProductID)
                .HasColumnType("bigint(20)")
                .HasComment("商品ID")
                .AddStringToLongConvert();

            entity.Property(e => e.ProductGroupID)
                .HasColumnType("bigint(20)")
                .HasComment("商品名称ID")
                .AddStringToLongConvert();

            entity.Property(e => e.ClassificationID)
                .HasColumnType("bigint(20)")
                .HasComment("商品分类ID")
                .AddStringToLongConvert();

            entity.Property(e => e.ProjectID)
                .HasColumnType("bigint(20)")
                .HasDefaultValueSql("'0'")
                .HasComment("项目ID")
                .AddStringToLongConvert();

            entity.Property(e => e.ReceiptAbstractID)
                .HasColumnType("bigint(20)")
                .HasComment("摘要ID")
                .AddStringToLongConvert();

            entity.Property(e => e.RowNum)
                .HasColumnType("int(11)")
                .HasComment("行号");

            entity.Property(e => e.Auxiliary1)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary2)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary3)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary4)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary5)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary6)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary7)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary8)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary9)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();

            entity.Property(e => e.Auxiliary10)
                .HasColumnType("bigint(20)")
                .HasComment("自定义辅助项")
                .AddStringToLongConvert();
        }
    }
}
