// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure
{
    public class fd_schedulesetConfiguration : IEntityTypeConfiguration<fd_scheduleset>
    {
        public void Configure(EntityTypeBuilder<fd_scheduleset> entity)
        {
            entity.HasKey(e => e.RecordId)
                .HasName("PRIMARY");

            entity.HasComment("付款排程设置表");

            entity.Property(e => e.RecordId)
                .HasColumnType("bigint(20)")
                .HasComment("自增列");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("datetime")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建日期");

            entity.Property(e => e.GroupId)
                .HasColumnType("bigint(20)")
                .HasComment("集团Id")
                .AddStringToLongConvert();

            entity.Property(e => e.Level)
                .HasColumnType("int(2)")
                .HasComment("等级（P1-P8）");

            entity.Property(e => e.ModifiedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("最后修改日期");

            entity.Property(e => e.OwnerId)
                .HasColumnType("bigint(20)")
                .HasComment("制单人");

            entity.Property(e => e.StayDay)
                .HasColumnType("int(3)")
                .HasComment("停留时长");
        }
    }
}
