// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure.EntityConfigurations
{
    public class fm_transferrealtimeConfiguration : IEntityTypeConfiguration<fm_transferrealtime>
    {
        public void Configure(EntityTypeBuilder<fm_transferrealtime> entity)
        {
            entity.HasKey(e => e.NumericalOrder)
                .HasName("PRIMARY");

            entity.HasIndex(e => e.EnterpriseID)
                .HasName("EnterpriseIDIndex");

            entity.Property(e => e.NumericalOrder)
                .HasColumnType("bigint(20)")
                .HasComment("凭证流水号");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建时间")
                .ValueGeneratedOnAddOrUpdate();

            entity.Property(e => e.DataDate)
                .IsRequired()
                .HasColumnType("varchar(10)")
                .HasComment("月份")
                .HasCharSet("utf8mb4")
                .HasCollation("utf8mb4_general_ci");

            entity.Property(e => e.EnterpriseID)
                .HasColumnType("bigint(20)")
                .HasComment("单位ID");

            entity.Property(e => e.TransferAccountsType)
                .HasColumnType("bigint(20)")
                .HasComment("结转类别");
        }
    }
}
