// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using System;
using FinanceManagement.Domain;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Metadata.Builders;

namespace FinanceManagement.Infrastructure.EntityConfigurations
{
    public class fm_transferrealtimedetailConfiguration : IEntityTypeConfiguration<fm_transferrealtimedetail>
    {
        public void Configure(EntityTypeBuilder<fm_transferrealtimedetail> entity)
        {
            entity.HasKey(e => e.RecordID)
                .HasName("PRIMARY");

            entity.HasIndex(e => e.NumericalOrderBiz)
                .HasName("NumericalOrderBizIndex");

            entity.HasIndex(e => e.NumericalOrderReceipt)
                .HasName("NumericalOrderReceiptIndex");

            entity.Property(e => e.RecordID)
                .HasColumnType("int(20)")
                .HasComment("主键");

            entity.Property(e => e.CreatedDate)
                .HasColumnType("timestamp")
                .HasDefaultValueSql("CURRENT_TIMESTAMP")
                .HasComment("创建日期")
                .ValueGeneratedOnAddOrUpdate();

            entity.Property(e => e.NumericalOrderBiz)
                .HasColumnType("bigint(20)")
                .HasComment("业务单据流水号");

            entity.Property(e => e.NumericalOrderBizDetail)
                .HasColumnType("bigint(20)")
                .HasComment("业务单据表体流水号");

            entity.Property(e => e.NumericalOrderReceipt)
                .HasColumnType("bigint(20)")
                .HasComment("凭证流水号");
        }
    }
}
