// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;

namespace FinanceManagement.Domain
{
    public partial class biz_datadict : EntityBase
    {
        public string DataDictID { get; set; }
        public string DataDictName { get; set; }
        public string DataDictType { get; set; }
        public string PID { get; set; }
        public string EnterpriseID { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}