// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Domain
{
    public class bsfile : EntityBase
    {
        [Key]
        public int RecordID { get; set; }
        public Guid Guid { get; set; }
        public string NumericalOrder { get; set; }
        public string FileType { get; set; }
        public int Type { get; set; }
        public string FileName { get; set; }
        public string FilePath { get; set; }
        public string Remarks { get; set; }
        public string EnterId { get; set; }
        public string OwnerID { get; set; }
        public DateTime CreationDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        [NotMapped]
        public string OwnerName { get; set; }
    }
}