// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Domain
{
    public partial class FD_PaymentReceivables : EntityBase
    {
        public FD_PaymentReceivables()
        {
            details = new List<FD_PaymentReceivablesDetail>();
        }
        [Key]
        public string NumericalOrder { get; set; }
        public Guid Guid { get; set; }
        public string SettleReceipType { get; set; }
        public DateTime DataDate { get; set; }
        public string TicketedPointID { get; set; }
        public string Number { get; set; }
        public string Remarks { get; set; }
        public string OwnerID { get; set; }
        public string EnterpriseID { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public string AttachmentNum { get; set; }
        public bool IsPush { get; set; }
        /// <summary>
        /// 是否来自集中支付
        /// </summary>
        public bool IsGroupPay { get; set; } = true;
        [NotMapped]
        public List<FD_PaymentReceivablesDetail> details { get; set; } = new List<FD_PaymentReceivablesDetail>();
        [NotMapped]
        public List<FD_PaymentExtend> extend { get; set; } = new List<FD_PaymentExtend>();

    }
}