// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Domain
{
    public partial class FD_PaymentExtend : EntityBase
    {
        [Key]
        public int RecordID { get; set; }
        public string NumericalOrder { get; set; }
        public string CollectionId { get; set; }
        public string PersonId { get; set; }
        public string AccountName { get; set; }
        public string BankDeposit { get; set; }
        public string BankAccount { get; set; }
        public decimal Amount { get; set; }
        [NotMapped]
        public decimal? Charges { get; set; }
        /// <summary>
        /// 金融专用流水号 只有在发起支付时才生成
        /// (收款单扩展表使用，用途：金融接口充值 使用的流水号，修改时候不能传相同流水 所以不能用单据流水号)
        /// </summary>
        public string TradeNo { get; set; }
        public Guid Guid { get; set; }
        public DateTime? ModifiedDate { get; set; }
        [NotMapped]
        public string AccoSubjectID { get; set; }
        [NotMapped]
        public string ExtendAccoSubjectID { get; set; }
        [NotMapped]
        public string AccoSubjectCode { get; set; }
        [NotMapped]
        public string ProjectID { get; set; }
        [NotMapped]
        public string ProductID { get; set; }
        [NotMapped]
        public string OrganizationSortID { get; set; }
        [NotMapped]
        public string SettleCustomerID { get; set; }
        [NotMapped]
        public string SettlePersonID { get; set; }
        [NotMapped]
        public string SettleMarketID { get; set; }
        [NotMapped]
        public string CustomerID { get; set; }
        [NotMapped]
        public string PersonID { get; set; }
        [NotMapped]
        public string MarketID { get; set; }
        [NotMapped]
        public string AccountID { get; set; }
        /// <summary>
        /// 支付结果
        /// </summary>
        public string PayResult { get; set; }
        /// <summary>
        /// 支付状态  0:未发起交易,1:成功,2:失败,3:交易中
        /// 收款单使用：1成功，2失败 （用途：往金融推送充值数据）↓
        /// https://confluence.nxin.com/pages/viewpage.action?pageId=65055307
        /// </summary>
        public int Status { get; set; }
        /// <summary>
        /// 用途
        /// </summary>
        public string PayUse { get; set; }
        /// <summary>
        /// 转账方式
        /// </summary>
        public int TransferType { get; set; }
        /// <summary>
        /// 是否复核
        /// </summary>
        public bool IsRecheck { get; set; }
        public string RecheckId { get; set; }
        /// <summary>
        /// 更新失败信息
        /// </summary>
        /// <param name="PayResult"></param>
        /// <param name="Status"></param>
        public void UpdateFailed(string PayResult,int Status)
        {
            this.PayResult = PayResult;
            this.Status = Status;
        }
        /// <summary>
        /// 发起支付，保存用途,转账方式
        /// </summary>
        /// <param name="PayUse"></param>
        /// <param name="TransferType"></param>
        public void UpdatePayInfo(string PayUse, int TransferType)
        {
            this.PayUse = PayUse;
            this.TransferType = TransferType;
        }
    }
}