// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Domain
{
    public partial class FD_PaymentReceivablesDetail : EntityBase
    {
        [Key]
        public int RecordID { get; set; }
        public string NumericalOrder { get; set; }
        public Guid Guid { get; set; }
        public string BusinessType { get; set; }
        public string ReceiptAbstractID { get; set; }
        public string PaymentTypeID { get; set; }
        public string AccountID { get; set; }
        public string CustomerID { get; set; }
        public string PersonID { get; set; }
        public string MarketID { get; set; }
        public string EnterpriseID { get; set; }
        public decimal? Amount { get; set; }
        public string Content { get; set; }
        public int? AttachCount { get; set; }
        public decimal? Charges { get; set; }
        [NotMapped]
        public string AccoSubjectID { get; set; }
        [NotMapped]
        public string AccoSubjectCode { get; set; }
        [NotMapped]
        public string ProjectID { get; set; }
        [NotMapped]
        public string ProductID { get; set; }
        [NotMapped]
        public string OrganizationSortID { get; set; }
    }
}