// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Domain
{
    public partial class fd_receivablesset : EntityBase
    {
        [Key]
        public string NumericalOrder { get; set; }
        public string EnterpriseID { get; set; }
        public string TicketedPointID { get; set; }
        public string ReceiptAbstractID { get; set; }
        public string Content { get; set; }
        public string CreditAccoSubjectID { get; set; }
        public string CostAccoSubjectID { get; set; }
        public string OwnerID { get; set; }
        public string Remarks { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        /// <summary>
        /// 标识是否删除
        /// </summary>
        /// 
        [NotMapped]
        public bool IsDelete { get; set; } = false;
        /// <summary>
        /// 单据类型（收款/会计凭证） APPID
        /// </summary>
        public string AppID { get; set; }
        /// <summary>
        /// 模板名称
        /// </summary>
        public string TemplateName { get; set; }
        /// <summary>
        /// 借方科目
        /// </summary>
        public string DebitAccoSubjectID { get; set; }
        /// <summary>
        /// 资金账户ID
        /// </summary>
        public string AccountID { get; set; }
        /// <summary>
        /// 结算方式
        /// </summary>
        public string PaymentType { get; set; }
        /// <summary>
        /// 凭证类别
        /// </summary>
        public string SettleReceipType { get; set; }
    }
}