// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Domain
{
    public partial class FD_SettleReceipt : EntityBase
    {
        public FD_SettleReceipt()
        {
            details = new List<FD_SettleReceiptDetail>();
        }
        [Key]
        public string NumericalOrder { get; set; }
        public Guid? Guid { get; set; }
        public string SettleReceipType { get; set; }
        public DateTime DataDate { get; set; }
        public string TicketedPointID { get; set; }
        public string Number { get; set; }
        public string AccountNo { get; set; }
        public string AttachmentNum { get; set; }
        public string Remarks { get; set; }
        public string EnterpriseID { get; set; }
        public string OwnerID { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        [NotMapped]
        public List<FD_SettleReceiptDetail> details { get; set; } = new List<FD_SettleReceiptDetail>();
    }

    /// <summary>
    /// 凭证导入专用
    /// </summary>
    public class EnterpriseInfo
    {
        public string EnterpriseName { get; set; }
        [Key]
        public string EnterpriseId { get; set; }
    }
    public class TicketPointInfo
    {
        [Key]
        public string TicketedPointId { get; set; }
        public string TicketedPointName { get; set; }
        public string EnterpriseId { get; set; }
    }
    public class SettleSummaryInfo
    {
        [Key]
        public string SettleSummaryId { get; set; }
        public string EnterpriseId { get; set; }
        public string SettleSummaryName { get; set; }
        public string SettleSummaryType { get; set; }
        /// <summary>
        ///3、摘要：预收充值冲抵（030102）
        /// </summary>
        public string Remarks { get; set; }
    }
    public class AccoSubjectInfo
    {
        [Key]
        public string AccoSubjectId { get; set; }
        public string AccoSubjectCode { get; set; }
        public string AccoSubjectName { get; set; }
        public string EnterpriseId { get; set; }
        /// <summary>
        /// 是否资金科目
        /// </summary>
        public bool IsTorF { get; set; }
        /// <summary>
        /// 是否贷方
        /// </summary>
        public bool IsLorR { get; set; }
        /// <summary>
        /// 是否项目核算
        /// </summary>
        public bool IsProject { get; set; }
        /// <summary>
        /// 是否客户核算
        /// </summary>
        public bool IsCus { get; set; }
        /// <summary>
        /// 是否员工核算
        /// </summary>
        public bool IsPerson { get; set; }
        /// <summary>
        /// 是否供应商核算
        /// </summary>
        public bool IsSup { get; set; }
        /// <summary>
        /// 是否部门核算
        /// </summary>
        public bool IsDept { get; set; }
        /// <summary>
        /// 是否类型核算
        /// </summary>
        public bool IsItem { get; set; }
        /// <summary>
        /// 是否现金核算
        /// </summary>
        public bool IsCash { get; set; }
        /// <summary>
        /// 是否银行核算
        /// </summary>
        public bool IsBank { get; set; }

    }
    public class ProjectInfo
    {
        [Key]
        public string ProjectID { get; set; }
        public string ProjectName { get; set; }
        public string EnterpriseID { get; set; }
    }
    public class MarketInfo
    {
        [Key]
        public string MarketId { get; set; }
        public string MarketName { get; set; }
        public string EnterpriseId { get; set; }
    }
    public class PersonInfo
    {
        [Key]
        public string PersonId { get; set; }
        public string PersonName { get; set; }
        public string EnterpriseId { get; set; }
    }
    /// <summary>
    /// 共用 获取 ID + 名称 公共类
    /// </summary>
    public class KeyNameInfo
    {
        [Key]
        public long ID { get; set; }
        public string Name { get; set; }
        public long EnterpriseId { get; set; }
    }
    /// <summary>
    /// 业务单元
    /// </summary>
    public class Inheritance
    {
        public string cAxis { get; set; }
        public string cFullName { get; set; }
        public string SortId { get; set; }
        public string Pid { get; set; }
        public string InheritanceId { get; set; }
        public bool IsEnd { get; set; }
        public string SortName { get; set; }
        public string SortRank { get; set; }
    }
    public class CusSupInfo
    {
        [Key]
        public string Id { get; set; }
        public string Name { get; set; }
        public string EnterpriseId { get; set; }
    }
    /// <summary>
    /// 商品代号  商品名称 共用
    /// </summary>
    public class ProductsInfo
    {
        [Key]
        public string ProductId { get; set; }
        public string ProductName { get; set; }
        public string EnterpriseId { get; set; }
    }
    public class ClassificationInfo
    {
        [Key]
        public string ClassificationID { get; set; }
        public string ClassificationName { get; set; }
        public string EnterpriseId { get; set; }
    }
    public class AccountsInfo
    {
        [Key]
        public string AccountId { get; set; }
        public string AccountName { get; set; }
        public string EnterpriseId { get; set; }
    }
    public class PayTypeInfo
    {
        [Key]
        public string PayTypeId { get; set; }
        public string PayTypeName { get; set; }
    }
    public class FD_SettleImport
    {
        public FD_SettleReceipt DataA { get; set; }
        public List<FD_SettleReceiptDetail> DataB { get; set; }
    }
    /// <summary>
    /// 会计凭证导入Excel 数据模型
    /// </summary>
    public class SettleExcelData
    {
        /// <summary>
        /// 序号
        /// </summary>
        public string Number { get; set; }
        /// <summary>
        /// 账务单位
        /// </summary>
        public string EnterpriseName { get; set; }
        /// <summary>
        /// 单据字
        /// </summary>
        public string TicketedPointName { get; set; }
        /// <summary>
        /// 日期
        /// </summary>
        public string DataDate { get; set; }
        /// <summary>
        /// 凭证类别
        /// </summary>
        public string SettleReceipType { get; set; }
        /// <summary>
        /// 摘要
        /// </summary>
        public string ReceiptAbstractName { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        public string Content { get; set; }
        /// <summary>
        /// 会计科目
        /// </summary>
        public string AccoSubjectName { get; set; }
        #region 会计科目辅助项数据
        /// <summary>
        /// 是否资金科目
        /// </summary>
        public bool IsTorF { get; set; }
        /// <summary>
        /// 是否贷方
        /// </summary>
        public bool IsLorR { get; set; }
        /// <summary>
        /// 是否项目核算
        /// </summary>
        public bool IsProject { get; set; }
        /// <summary>
        /// 是否客户核算
        /// </summary>
        public bool IsCus { get; set; }
        /// <summary>
        /// 是否员工核算
        /// </summary>
        public bool IsPerson { get; set; }
        /// <summary>
        /// 是否供应商核算
        /// </summary>
        public bool IsSup { get; set; }
        /// <summary>
        /// 是否部门核算
        /// </summary>
        public bool IsDept { get; set; }
        /// <summary>
        /// 是否类型核算
        /// </summary>
        public bool IsItem { get; set; }
        /// <summary>
        /// 是否现金核算
        /// </summary>
        public bool IsCash { get; set; }
        /// <summary>
        /// 是否银行核算
        /// </summary>
        public bool IsBank { get; set; }
        #endregion
        /// <summary>
        /// 员工
        /// </summary>
        public string PersonName { get; set; }
        /// <summary>
        /// 部门
        /// </summary>
        public string MarketName { get; set; }
        /// <summary>
        /// 客/商
        /// </summary>
        public string CustomerName { get; set; }
        /// <summary>
        /// 项目
        /// </summary>
        public string ProjectName { get; set; }
        /// <summary>
        /// 商品代号
        /// </summary>
        public string ProductName { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        public string ProductGroupName { get; set; }
        /// <summary>
        /// 商品分类
        /// </summary>
        public string ClassificationName { get; set; }
        /// <summary>
        /// 借方
        /// </summary>
        public string Debit { get; set; }
        /// <summary>
        /// 贷方
        /// </summary>
        public string Credit { get; set; }
        /// <summary>
        /// 资金账户
        /// </summary>
        public string AccountName { get; set; }
        /// <summary>
        /// 结算方式
        /// </summary>
        public string PaymentTypeName { get; set; }
        /// <summary>
        /// 附单据张数
        /// </summary>
        public string AttachmentNum { get; set; }
        public string OrganizationSortID { get; set; }
        public string EnterpriseID { get; set; }
    }
    /// <summary>
    /// 根据系统选项获取整个集团所有单位 该系统选项使用情况  开启状况
    /// </summary>
    public class OptionInfo
    {
        public bool OptionSwitch { get; set; }
        [Key]
        public string EnterpriseId { get; set; }
        public string EnterpriseName { get; set; }
    }
    /// <summary>
    /// 会计凭证集团导出 数据模型
    /// </summary>
    public class ExportVoucher
    {
        [Key]
        public long RecordID { get; set; }
        /// <summary>
        /// 单位ID
        /// </summary>
        public long EnterpriseID { get; set; }
        /// <summary>
        /// 单位名称
        /// </summary>
        public string EnterpriseName { get; set; }
        /// <summary>
        /// 凭证日期
        /// </summary>
        public string DataDate { get; set; }
        /// <summary>
        /// 凭证类型
        /// </summary>
        public string SettleReceipTypeName { get; set; }
        /// <summary>
        /// 单据字号
        /// </summary>
        public string TicketPointNumber { get; set; }
        /// <summary>
        /// 摘要名称
        /// </summary>
        public string ReceiptAbstractName { get; set; }
        /// <summary>
        /// 会计科目
        /// </summary>
        public string AccoSubjectFullName { get; set; }
        /// <summary>
        /// 人员名称
        /// </summary>
        public string Name { get; set; }
        /// <summary>
        /// 部门名称
        /// </summary>
        public string MarketName { get; set; }
        /// <summary>
        /// 客户/供应商
        /// </summary>
        public string CustomerName { get; set; }
        /// <summary>
        /// 项目名称
        /// </summary>
        public string ProjectName { get; set; }
        /// <summary>
        /// 商品代号
        /// </summary>
        public string ProductName { get; set; }
        /// <summary>
        /// 商品名称
        /// </summary>
        public string ProductGroupName { get; set; }
        /// <summary>
        /// 商品分类
        /// </summary>
        public string ClassificationName { get; set; }
        /// <summary>
        /// 借方金额
        /// </summary>
        public decimal? Debit { get; set; }
        /// <summary>
        /// 贷方金额
        /// </summary>
        public decimal? Credit { get; set; }
        /// <summary>
        /// 资金账户名称
        /// </summary>
        public string AccountFullName { get; set; }
        /// <summary>
        /// 结算方式
        /// </summary>
        public string PaymentTypeName { get; set; }
        /// <summary>
        /// 所属单位/业务单元
        /// </summary>
        public string SortName { get; set; }
        /// <summary>
        /// 现金流量项目
        /// </summary>
        public string FinancialStatementName { get; set; }
        /// <summary>
        /// 附单据张数
        /// </summary>
        public string AttachmentNum { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 制单人
        /// </summary>
        public string OwnerName { get; set; }
        /// <summary>
        /// 审核人
        /// </summary>
        public string AuditName { get; set; }
        /// <summary>
        /// 内容
        /// </summary>
        public string Content { get; set; }
    }
}