// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;

namespace FinanceManagement.Domain
{
    public partial class fd_scheduleplan : EntityBase
    {
        [Key]
        public string NumericalOrder { get; set; }
        public string GroupId { get; set; }
        public DateTime? ApplyData { get; set; }
        public string ApplyEnterpriseId { get; set; }
        public string ApplyMenuId { get; set; }
        public string ApplyNumericalOrder { get; set; }
        public string PayNumericalOrder { get; set; }
        public string ApplyPayContent { get; set; }
        public string ApplyContactType { get; set; }
        public string ApplyContactEnterpriseId { get; set; }
        public string ApplyEmergency { get; set; }
        public DateTime? ApplyDeadLine { get; set; }
        public decimal? ApplyAmount { get; set; }
        public decimal? ApplySurplusAmount { get; set; }
        public decimal? PayAmount { get; set; }
        public DateTime? DeadLine { get; set; }
        public int? Level { get; set; }
        public string SettlementMethod { get; set; }
        /// <summary>
        /// 1：排程中,2:已排程,-1:历史（排程过程）
        /// </summary>
        public int? ScheduleStatus { get; set; }
        public long OwnerId { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
    /// <summary>
    /// OData查询类
    /// </summary>
    public class fd_scheduleplanEntity
    {
        [Key]
        public string NumericalOrder { get; set; }
        [NotMapped]
        public int count { get; set; } = 0;
        public string GroupId { get; set; }
        public DateTime? ApplyData { get; set; }
        public string ApplyEnterpriseId { get; set; }
        public string ApplyEnterpriseName { get; set; }
        public string ApplyMenuId { get; set; }
        public string ApplyMenuName { get; set; }
        public string ApplyNumericalOrder { get; set; }
        public string ApplyPayContent { get; set; }
        public string ApplyContactType { get; set; }
        public string ApplyContactTypeName { get; set; }
        public string ApplyContactEnterpriseId { get; set; }
        public string ApplyContactEnterpriseName { get; set; }
        public string ApplyEmergency { get; set; }
        public DateTime? ApplyDeadLine { get; set; }
        public decimal? ApplyAmount { get; set; }
        public decimal? ApplySurplusAmount { get; set; }
        public decimal? PayAmount { get; set; }
        public DateTime? DeadLine { get; set; }
        public int? Level { get; set; }
        public string SettlementMethod { get; set; }
        public int? ScheduleStatus { get; set; }
        public long OwnerId { get; set; }
        public string OwnerName { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        /// <summary>
        /// 排程计数
        /// </summary>
        [NotMapped]
        public int ScheduleCount { get; set; }
        /// <summary>
        /// 排程计数集合
        /// </summary>
        [NotMapped]
        public string ScheduleCountList { get; set; }
        /// <summary>
        /// 是否排程数据
        /// </summary>
        [NotMapped]
        public bool IsSchedule { get; set; } = true;
        /// <summary>
        /// 申请接口专用字段
        /// </summary>
        /// 
        [NotMapped]
        public string ReceiptAbstractCode { get; set; }
        /// <summary>
        /// 申请地址（已拼好，直接使用）
        /// </summary>
        public string cAHrefDetails { get; set; }
    }
    public class fd_scheduleplanReportEntity 
    {
        /// <summary>
        /// 流水号
        /// </summary>
        [Key]
        public string NumericalOrder { get; set; }
        [NotMapped]
        public int count { get; set; } = 0;
        /// <summary>
        /// 集团Id
        /// </summary>
        public string GroupId { get; set; }
        /// <summary>
        /// 申请日期
        /// </summary>
        public DateTime? ApplyData { get; set; }
        /// <summary>
        /// 申请单位id
        /// </summary>
        public string ApplyEnterpriseId { get; set; }
        /// <summary>
        /// 申请单位名称
        /// </summary>
        public string ApplyEnterpriseName { get; set; }
        /// <summary>
        /// 申请单据类型
        /// </summary>
        public string ApplyMenuId { get; set; }
        /// <summary>
        /// 申请单据类型
        /// </summary>
        public string ApplyMenuName { get; set; }
        /// <summary>
        /// 申请流水号
        /// </summary>
        public string ApplyNumericalOrder { get; set; }
        /// <summary>
        /// 申请支出内容
        /// </summary>
        public string ApplyPayContent { get; set; }
        /// <summary>
        /// 申请往来类型
        /// </summary>
        public string ApplyContactType { get; set; }
        /// <summary>
        /// 申请往来类型
        /// </summary>
        public string ApplyContactTypeName { get; set; }
        /// <summary>
        /// 申请往来单位
        /// </summary>
        public string ApplyContactEnterpriseId { get; set; }
        /// <summary>
        /// 申请往来单位
        /// </summary>
        public string ApplyContactEnterpriseName { get; set; }
        /// <summary>
        /// 申请是否紧急
        /// </summary>
        public string ApplyEmergency { get; set; }
        /// <summary>
        /// 申请付款到期日
        /// </summary>
        public DateTime? ApplyDeadLine { get; set; }
        /// <summary>
        /// 申请金额
        /// </summary>
        public decimal? ApplyAmount { get; set; }
        /// <summary>
        /// 申请剩余金额
        /// </summary>
        public decimal? ApplySurplusAmount { get; set; }
        /// <summary>
        /// 计划支付金额
        /// </summary>
        public decimal? PayAmount { get; set; }
        /// <summary>
        /// 计划付款日
        /// </summary>
        public DateTime? DeadLine { get; set; }
        /// <summary>
        /// 付款优先级
        /// </summary>
        public int? Level { get; set; }
        /// <summary>
        /// 结算方式
        /// </summary>
        public string SettlementMethod { get; set; }
        /// <summary>
        /// 排程状态（0:未排（只用于程序中 数据库不做存储）,1：排程中,2:已排程,3:已排程，并以付款,4:关闭,-1:历史（排程过程））
        /// </summary>
        public int? ScheduleStatus { get; set; }
        /// <summary>
        /// 制单人
        /// </summary>
        public long OwnerId { get; set; }
        /// <summary>
        /// 制单人
        /// </summary>
        public string OwnerName { get; set; }
        /// <summary>
        /// 创建时间
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改时间
        /// </summary>
        public DateTime ModifiedDate { get; set; }
        /// <summary>
        /// 排程计数
        /// </summary>
        [NotMapped]
        public int ScheduleCount { get; set; }
        /// <summary>
        /// 排程计数集合
        /// </summary>
        [NotMapped]
        public string ScheduleCountList { get; set; }
        /// <summary>
        /// 是否排程数据
        /// </summary>
        [NotMapped]
        public bool IsSchedule { get; set; } = true;
        /// <summary>
        /// 申请接口专用字段
        /// </summary>
        /// 
        [NotMapped]
        public string ReceiptAbstractCode { get; set; }
        /// <summary>
        /// 付款日期
        /// </summary>
        public DateTime? PaymentDataDate { get; set; }
        /// <summary>
        /// 实际支付金额
        /// </summary>
        public decimal? PaymentAmount { get; set; }
        public string cAHrefDetails { get; set; }
        public string PayNumericalOrder { get; set; }
        public string PaymentNumber { get; set; }
    }
    public class MenuInfo
    {
        [Key]
        public string MenuId { get; set; }
        public string MenuName { get; set; }
        public string DetailUrl { get; set; }
    }
    public class ManagerItem
    {
        /// <summary>
        /// 
        /// </summary>
        public string boid { get; set; }
        /// <summary>
        /// 李明测试
        /// </summary>
        public string name { get; set; }
        /// <summary>
        /// 负责人
        /// </summary>
        public string roleName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string personId { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string roleType { get; set; }
    }

    public class OrgRoot
    {
        /// <summary>
        /// 
        /// </summary>
        public List<ManagerItem> manager { get; set; }
        /// <summary>
        /// 北京市/市辖区/西城区
        /// </summary>
        public string areaName { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string pid { get; set; }
        /// <summary>
        /// 天桥街道鹞儿胡同
        /// </summary>
        public string adress { get; set; }
        /// <summary>
        /// 
        /// </summary>
        public string enterpriseId { get; set; }
        /// <summary>
        /// 北京助农
        /// </summary>
        public string enterpriseName { get; set; }
        /// <summary>
        /// 北京市/市辖区/西城区天桥街道鹞儿胡同
        /// </summary>
        public string fullAdress { get; set; }
        /// <summary>
        /// 负责人名称
        /// </summary>
        public string ChargeName { get; set; }
    }
    public class ApplyRelation
    {
        [Key]
        public Guid Guid { get; set; }
        /// <summary>
        /// 申请流水
        /// </summary>
        public string NumericalOrder { get; set; }
        /// <summary>
        /// 单位/客户/人员/部门
        /// </summary>
        public string Id { get; set; }
        public string Name { get; set; }
    }
}