// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;

namespace FinanceManagement.Domain
{
    public partial class FD_ScReceivable : EntityBase
    {
        public string orderId { get; set; }
        public string dataDate { get; set; }
        public string enterpriseId { get; set; }
        public string customerId { get; set; }
        public decimal amount { get; set; }        
        public string ownerId { get; set; }
    }
}