// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinanceManagement.Domain
{
    public partial class MS_FormulaProductPrice : EntityBase
    {
        public MS_FormulaProductPrice() 
        {
            Lines = new List<MS_FormulaProductPriceDetail>();
            ExtList=new List<MS_FormulaProductPriceExt> ();
            CreatedDate=ModifiedDate=DateTime.Now;
        }
        public void AddDetail(MS_FormulaProductPriceDetail detail)
        {
            Lines.Add(detail);
        }
        public void AddExt(MS_FormulaProductPriceExt ext)
        {
            ExtList.Add(ext);
        }

        public void Update(DateTime DataDate)
        {
            this.DataDate = DataDate;
            this.ModifiedDate = DateTime.Now;
        }
        [Key]
        public string NumericalOrder { get; set; }
        public string GroupID { get; set; }
        public DateTime DataDate { get; set; }
        public string Number { get; set; }
        public string OwnerID { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
        public List<MS_FormulaProductPriceDetail> Lines { get; set; }
        public List<MS_FormulaProductPriceExt> ExtList { get; set; }
    }
    public partial class MS_FormulaProductPriceDetail : EntityBase
    {
        [Key]
        public int RecordID { get; set; }
        public string NumericalOrder { get; set; }
        public string ProductID { get; set; }
        public string Specification { get; set; }
        public decimal? StandardPack { get; set; }
        public string MeasureUnit { get; set; }
        public decimal? MarketPrice { get; set; }
        public string Remarks { get; set; }
        public DateTime ModifiedDate { get; set; }
        public MS_FormulaProductPrice MS_FormulaProductPrice { get; set; }
    }
    public partial class MS_FormulaProductPriceExt : EntityBase
    {
        [Key]
        public int RecordID { get; set; }
        public string NumericalOrder { get; set; }
        public string EnterpriseID { get; set; }
        public DateTime ModifiedDate { get; set; }
        public MS_FormulaProductPrice MS_FormulaProductPrice { get; set; }
    }
}