// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinanceManagement.Domain
{
    public partial class fm_transferrealtime : EntityBase
    {
        [Key]
        public long NumericalOrder { get; set; }
        public long EnterpriseID { get; set; }
        public string DataDate { get; set; }
        public long TransferAccountsType { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}