// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinanceManagement.Domain
{
    public partial class fm_transferrealtimedetail : EntityBase
    {
        [Key]
        public int RecordID { get; set; }
        public long NumericalOrderReceipt { get; set; }
        public long NumericalOrderBiz { get; set; }
        public long NumericalOrderBizDetail { get; set; }
        public DateTime CreatedDate { get; set; }
    }
}