// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

namespace FinanceManagement.Domain
{
    public partial class fm_voucheramortizationrelated : EntityBase
    {
        [Key]
        public int RecordID { get; set; }
        public long NumericalOrderVoucher { get; set; }
        public long NumericalOrderSettl { get; set; }
        public long NumericalOrderStay { get; set; }
        public long NumericalOrderInto { get; set; }
        public decimal VoucherAmount { get; set; }
        public DateTime CreatedDate { get; set; }
        public DateTime ModifiedDate { get; set; }
    }
}