// <auto-generated> This file has been auto generated by EF Core Power Tools. </auto-generated>
using Architecture.Seedwork.Domain;
using System;
using System.Collections.Generic;
using System.ComponentModel.DataAnnotations;

#nullable disable

namespace FinanceManagement.Domain
{
    public partial class FmCostproject : EntityBase
    {
        /// <summary>
        /// 费用项目ID
        /// </summary>
        [Key]
        public string CostProjectId { get; set; }

        /// <summary>
        /// 日期
        /// </summary>
        public DateTime DataDate { get; set; }
        /// <summary>
        /// 单位ID
        /// </summary>
        public string EnterpriseId { get; set; }

        public string CostProjectName { get; set; }
        /// <summary>
        /// 项目分类
        /// </summary>
        public string? CostProjectTypeId { get; set; }
        /// <summary>
        /// 是否启用
        /// </summary>
        public ulong? IsUse { get; set; }
        /// <summary>
        /// 序号
        /// </summary>
        public int? OrderNumber { get; set; }
        /// <summary>
        /// 备注
        /// </summary>
        public string Remarks { get; set; }
        /// <summary>
        /// 制单人ID
        /// </summary>
        public string OwnerId { get; set; }
        /// <summary>
        /// 创建日期
        /// </summary>
        public DateTime CreatedDate { get; set; }
        /// <summary>
        /// 修改日期
        /// </summary>
        public DateTime ModifiedDate { get; set; }
        /// <summary>
        /// 费用编码
        /// </summary>
        public string CostProjectCode { get; set; }
        /// <summary>
        /// 归集类型
        /// </summary>
        public string CollectionType { get; set; }
        /// <summary>
        /// 分摊方式
        /// </summary>
        public string AllocationType { get; set; }
        /// <summary>
        /// 取数来源
        /// </summary>
        public string DataSource { get; set; }

        /// <summary>
        /// 修改人
        /// </summary>
        public string ModifiedOwnerID { get; set; }

        /// <summary>
        /// 绑定预置项
        /// </summary>
        public string PresetItem { get; set; }
    }
}